# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CD

on: 
  workflow_dispatch:
    inputs:
      run-id:
        required: true
        description: 'The run-id of the ci pipeline to download the nuget package from'
  push:
    tags:
    - '*.*.*'
   
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Download nuget package
        uses: actions/download-artifact@v4.1.5
        with:
          name: Productive.Modulith.1.0.1.nupkg
          github-token: ${{ secrets.modulith_actions }}
          run-id: ${{ inputs.run-id }}
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          
      - name: Push Package to NuGet.org
        env:
          NUGET_URL: https://api.nuget.org/v3/index.json
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push *.nupkg
